[project]
name = "libcat"
version = "0.1.0"
description = "A versatile program for Copy Cataloging"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pymupdf>=1.26.3",
    "regex>=2025.7.34",
    "requests>=2.32.4",
    "selectolax>=0.3.32",
]
